package conformance

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the report as the committed document. It is
// written for a reader deciding whether to trust the number, so the
// order is: what was measured against, the totals, then everything
// that was not attempted, then everywhere the two implementations
// disagree. The prose that explains what any of it means lives in
// docs/CONFORMANCE.md; this file states facts and nothing else.
func (r Report) Markdown() string {
	var b strings.Builder

	b.WriteString(
		"<!-- Code generated by internal/cmd/confreport; " +
			"DO NOT EDIT. -->\n" +
			"<!-- Regenerate with: go run ./internal/cmd/confreport " +
			"-->\n\n" +
			"# Conformance report\n\n" +
			"Measured by running every in-scope case of the cel-spec\n" +
			"simple conformance corpus against a fresh cel4postgres\n" +
			"install, and the same cases against cel-go under the same\n" +
			"environment. See [CONFORMANCE.md](CONFORMANCE.md) for what\n" +
			"is in scope and why, and for the reasoning behind the\n" +
			"divergences listed at the end.\n\n",
	)

	b.WriteString("## Measured against\n\n")
	b.WriteString("| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| cel-spec corpus | `%s` |\n", r.CelSpec)
	fmt.Fprintf(&b, "| cel-go | `%s` |\n", r.CelGo)
	fmt.Fprintf(&b, "| PostgreSQL | %s |\n\n", r.Postgres)

	b.WriteString("## Summary\n\n")
	attempted := r.Totals.Passed + r.Totals.Failed
	inSkippedFiles := 0
	for _, file := range r.SkippedFiles {
		inSkippedFiles += file.Cases
	}
	fmt.Fprintf(&b,
		"**%d of %d attempted cases passed, %d failed.**\n\n"+
			"The corpus holds %d cases in %d files. %d cases in %d\n"+
			"files were attempted. The other %d were not: %d in the\n"+
			"files listed under *Files not attempted*, and %d named\n"+
			"cases inside files that were.\n\n",
		r.Totals.Passed, attempted, r.Totals.Failed,
		r.Totals.Cases, r.Totals.Files,
		attempted, r.Totals.Files-r.Totals.SkippedFiles,
		r.Totals.Skipped, inSkippedFiles, len(r.SkippedCases),
	)

	b.WriteString("## Per file\n\n")
	b.WriteString(
		"`env` is the environment parameter the file runs under: each\n" +
			"extension file enables exactly the extension it exercises,\n" +
			"and nothing is enabled by default.\n\n",
	)
	b.WriteString(
		"| file | env | cases | passed | skipped | failed |\n" +
			"|---|---|--:|--:|--:|--:|\n",
	)
	for _, file := range r.Files {
		fmt.Fprintf(&b, "| %s | `%s` | %d | %d | %d | %d |\n",
			file.Name, file.Env, file.Cases,
			file.Passed, file.Skipped, file.Failed)
	}
	b.WriteString("\n")

	b.WriteString("## Files not attempted\n\n")
	b.WriteString("| file | cases | reason |\n|---|--:|---|\n")
	for _, file := range r.SkippedFiles {
		fmt.Fprintf(&b, "| %s | %d | %s |\n",
			file.Name, file.Cases, file.Reason)
	}
	b.WriteString("\n")

	r.writeSkippedCases(&b)
	r.writeFailures(&b)
	r.writeDivergences(&b)

	return b.String()
}

// writeSkippedCases lists every unattempted case by name, grouped by
// file and reason. The count alone would be half a fact: a skip is
// only visible if the thing skipped is named.
func (r Report) writeSkippedCases(b *strings.Builder) {
	fmt.Fprintf(b,
		"## Cases not attempted, inside attempted files\n\n"+
			"%d cases, each named here.\n\n", len(r.SkippedCases))

	grouped := map[string][]string{}
	for _, skip := range r.SkippedCases {
		key := skip.File + "\x00" + skip.Reason
		grouped[key] = append(grouped[key],
			skip.Section+"/"+skip.Name)
	}

	keys := make([]string, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		file, reason, _ := strings.Cut(key, "\x00")
		cases := grouped[key]
		sort.Strings(cases)
		fmt.Fprintf(b, "### %s — %s (%d)\n\n", file, reason, len(cases))
		for _, name := range cases {
			fmt.Fprintf(b, "- `%s`\n", name)
		}
		b.WriteString("\n")
	}
}

func (r Report) writeFailures(b *strings.Builder) {
	if len(r.Failures) == 0 {
		return
	}

	fmt.Fprintf(b, "## Failures\n\n%d cases disagreed with the corpus.\n\n",
		len(r.Failures))
	for _, failure := range r.Failures {
		fmt.Fprintf(b, "### `%s/%s/%s`\n\n```\n%s\n```\n\n",
			failure.File, failure.Section, failure.Name,
			failure.Detail)
	}
}

// writeDivergences names every case the two implementations judge
// differently. cel4postgres follows the corpus where the two
// disagree, so an entry here is nearly always a case cel-go itself
// does not satisfy -- stated case by case rather than asserted.
func (r Report) writeDivergences(b *strings.Builder) {
	b.WriteString(
		"## Divergences from cel-go\n\n" +
			"Cases where the two implementations reach different\n" +
			"verdicts against the corpus expectation. Both sides ran\n" +
			"under the same environment and were judged by the same\n" +
			"comparator.\n\n",
	)

	if len(r.Divergences) == 0 {
		b.WriteString("None: the two agree on every attempted case.\n")
		return
	}

	fmt.Fprintf(b, "%d cases.\n\n", len(r.Divergences))
	for _, d := range r.Divergences {
		fmt.Fprintf(b, "### `%s/%s/%s`\n\n```\n%s\n```\n\n",
			d.File, d.Section, d.Name, d.Expr)
		fmt.Fprintf(b, "- cel4postgres — %s\n", d.Cel4Postgres)
		fmt.Fprintf(b, "- cel-go — %s\n\n", d.CelGo)
	}
}
