// Package conformance runs the cel-spec conformance corpus against
// cel4postgres. The non-test files here are the parts the skip-list
// generator (internal/cmd/skipgen) also needs: what is skipped, and
// under which environment each file runs.
package conformance

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/emfga/cel4postgres/internal/corpus"
)

// SkippedFiles names the corpus files the suite does not attempt at
// all, each with its reason. The suite prints this list on every run:
// the difference between "not implemented" and "not attempted" must
// stay visible, and coverage must never shrink silently.
var SkippedFiles = map[string]string{
	"proto2":     "requires protobuf descriptors",
	"proto3":     "requires protobuf descriptors",
	"enums":      "requires protobuf descriptors",
	"wrappers":   "requires proto3 TestAllTypes + Any unpacking",
	"proto2_ext": "requires proto2 extensions",
	"block_ext":  "cel-go-internal cel.block form; no consumer",
}

// skipReason returns the reason a case is skipped, or "" to run it.
func skipReason(file, section, name string) string {
	if reason, ok := SkippedFiles[file]; ok {
		return reason
	}
	return skippedCases[file+"/"+section+"/"+name]
}

// GenerateSkippedCases scans the corpus for cases inside included
// files that need protobuf descriptors. It is the single source of
// the generated skipped_cases.go (via internal/cmd/skipgen) and of
// the test that keeps that file current, so the committed list cannot
// drift from the corpus.
func GenerateSkippedCases() (map[string]string, error) {
	files, err := corpus.Files()
	if err != nil {
		return nil, err
	}

	skipped := map[string]string{}
	for _, file := range files {
		if _, ok := SkippedFiles[file]; ok {
			continue
		}
		parsed, err := corpus.Load(file)
		if err != nil {
			return nil, err
		}
		for _, section := range parsed.GetSection() {
			for _, test := range section.GetTest() {
				if corpus.DescriptorDependent(test) {
					key := file + "/" + section.GetName() +
						"/" + test.GetName()
					skipped[key] = "requires protobuf descriptors"
				}
			}
		}
	}

	return skipped, nil
}

// RenderSkippedCases renders the generated map as the Go source of
// skipped_cases.go.
func RenderSkippedCases(skipped map[string]string) string {
	keys := make([]string, 0, len(skipped))
	for key := range skipped {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString(
		"// Code generated by internal/cmd/skipgen; DO NOT EDIT.\n" +
			"//\n" +
			"// Every entry is a case inside an included corpus file " +
			"whose content\n" +
			"// references the descriptor-backed test messages. " +
			"Regenerate with:\n" +
			"//\n" +
			"//\tgo run ./internal/cmd/skipgen\n" +
			"package conformance\n\n" +
			"var skippedCases = map[string]string{\n",
	)
	for _, key := range keys {
		fmt.Fprintf(&b, "\t%q: %q,\n", key, skipped[key])
	}
	b.WriteString("}\n")

	source, err := format.Source([]byte(b.String()))
	if err != nil {
		// The template is static; a formatting failure means the
		// template itself broke, which the skip-list test catches.
		return b.String()
	}
	return string(source)
}
